### ISSUE TITLE
MMIE Score model is invalid

### ISSUE THREAD

**Issue by XuyaoWang** [Lillianwei-h/MMIE#2]
Thank you for your hard work. It appears that the MMIE-Score model is currently inaccessible: one [Hugging Face link](https://huggingface.co/Lillianwei/MMIE-Score) is set to private, and the other [Hugging Face link](https://huggingface.co/MMIE/MMIE-Score/tree/main) seems to be empty. Could you please provide an estimated release date for the MMIE-Score model? I sincerely appreciate your efforts.

**Comment by XuyaoWang** [comment]
Additionally, please organize your [requirements.txt](https://github.com/Lillianwei-h/MMIE/blob/main/requirements.txt) file by removing unnecessary dependencies and adjusting it to a format that supports installation via ```pip install -r requirements.txt```.

**Comment by Lillianwei-h** [comment]
I am sorry for the mistake of url in the paragraph and I have updated it, but I can open the link by clicking the button under the title and it's not private. Can you try to use this link https://huggingface.co/MMIE/MMIE-Score ?

**Comment by XuyaoWang** [comment]
> I am sorry for the mistake of url in the paragraph and I have updated it, but I can open the link by clicking the button under the title and it's not private. Can you try to use this link https://huggingface.co/MMIE/MMIE-Score ?

I have checked the [link](https://huggingface.co/MMIE/MMIE-Score/tree/main) and found that it only contains the ```README.md``` and ```.gitattributes``` files, with no model weight files included.

**Comment by Lillianwei-h** [comment]
I am so so so sorry! Thank you for discovering this big problem😭. I have just uploaded the model weight.

**Comment by Lillianwei-h** [comment]
I have fixed  requirements.txt and tested it in a new environment. It should work now. I am so sorry for the inconvenience😭.

**Comment by XuyaoWang** [comment]
Thank you very much for your response, but I may need to point out that it seems you've uploaded too many unnecessary files to the [Hugging Face repository](https://huggingface.co/MMIE/MMIE-Score/tree/main), such as:

1. [Training logs](https://huggingface.co/MMIE/MMIE-Score/blob/main/trainer_state.json)
2. [Absolute paths](https://huggingface.co/MMIE/MMIE-Score/blob/main/config.json) of the models
3. Unnecessary models (I suspect you ultimately used [internvl](https://huggingface.co/MMIE/MMIE-Score/blob/main/modeling_internvl_chat.py) rather than [phi3](https://huggingface.co/MMIE/MMIE-Score/blob/main/modeling_phi3.py) as the base model)

Please double-check for any additional unnecessary files. There's no rush—your work is valuable and worth the time.

Additionally, **we are developing a TI2TI model based on Chameleon and would like to know if we can participate in your leaderboard once we've completed the development**. We are also working on multimodal models and look forward to potential future collaboration.

**Comment by Lillianwei-h** [comment]
I have deleted the files mentioned in point 1 and 2. Actually phi3 is used as the language model of InternVL2-4B, so it's not unnecessary. Thank you so much for your kind reminder!

Of course you can participate in our leaderboard! Just contact us when your project is completed~
