### ISSUE TITLE
Model does not provide meaningful scores

### ISSUE THREAD

**Issue by arunmallya** [Lillianwei-h/MMIE#3]
I tried running the model using the command `python main.py --input_dir debug/ --input_name samples.json` on 3 samples constructed from the examples in the paper's appendix. 
<img width="705" alt="Screenshot 2024-11-07 at 4 26 55 PM" src="https://github.com/user-attachments/assets/52f1bec3-4ca9-4ecb-a6ad-cab90e5cda80">
It gives a score of 5 for all 3 samples (a full score for the SA task), even when the interleaved inputs and outputs do not make sense together. All the required files for reproduction, as well as the output are attached here - [debug.zip](https://github.com/user-attachments/files/17670925/debug.zip)

I am guessing this is not the desired model behavior? Any idea what is going wrong?

**Comment by Lillianwei-h** [comment]
Thank you for your interest in our work! May I ask if you use the latest MMIE-Score model? Since there was something wrong with the old version and we fix it about 2 weeks ago. If the problem still exists, please let us know and we will check it again.

**Comment by arunmallya** [comment]
Huggingface automatically downloads the model when you run the script for the first time.   I'm guessing that downloads the latest model, unless there's something wrong there.

**Comment by Lillianwei-h** [comment]
Oh, I just noticed that you use the screenshot from the appendix. In my experience, if you crop or resize the original output image, the result of the MMIE-Score would be significantly unstable, although I haven't figured out the reason yet. I thought there might be some problems within the original InternVL model. Maybe you can try to use the direct result of any model and set the size of the images to 512px*512px?

**Comment by StephenQSstarThomas** [comment]
Our primary results have shown that the images given should be constrained to 512*512 pixels, any other formats would lead to significantly different results and conclusions, thus leading to bias and unfairness. May you try using the direct images generated by the listing models please? Many thanks!

**Comment by StephenQSstarThomas** [comment]
Another thing to say, the examplar images shown in appendix is preprocessed, to be exactly, twisted or turned for some times to fit our paper size lol. So utilizing the graphs in our appendix may lead to different results.

**Comment by arunmallya** [comment]
I originally tried on 512 x 512 images, that I cannot share publicly. I had the same issues as the screenshots I shared. Every input gave the same output.

**Comment by Lillianwei-h** [comment]
If the model is the latest version and the input data is correct, I can only guess that it's because our training data does not contain such irrelevant cases, and the model cannot make a correct judgment. Thank you for your feedback, we will continue to improve our model!
